import pymysql
db = pymysql.connect(host='localhost',user='root',passwd='', database="projectdb")
cursor = db.cursor()
def act(query):
    cursor.execute(query)


sql=("DROP TABLE get_service")
act(sql)
db.commit()

sql=("DROP TABLE is_provided_to")
act(sql)
db.commit()
sql=("DROP TABLE costumer_registered_to_services")
act(sql)
db.commit()
sql=("DROP TABLE no_registered_services")
act(sql)
db.commit()
sql=("DROP TABLE registered_services")
act(sql)
db.commit()
sql=("DROP TABLE services")
act(sql)
db.commit()
sql=("DROP TABLE have_access")
act(sql)
db.commit()
sql=("DROP TABLE visit")
act(sql)
db.commit()
sql=("drop table costumer_email")
act(sql)
db.commit()
sql=("drop table costumer_mobile;")
act(sql)
db.commit()
sql=("DROP TABLE costumer")
act(sql)
db.commit()
sql=("DROP TABLE places")
act(sql)
db.commit()
sql=("DROP view erwthma7")
act(sql)
db.commit()
sql=("DROP view erwthma9")
act(sql)
db.commit()
sql=("DROP view erwthma10")
act(sql)
db.commit()
sql=("DROP view erwthma8a")
act(sql)
db.commit()
sql=("DROP view erwthma8b")
act(sql)
db.commit()